#!/usr/bin/env python

import sys
from collections import defaultdict, Counter

f1 = open(sys.argv[1])
f2 = open(sys.argv[2])

dict1 = defaultdict(list)
dict2 = defaultdict(list)

for line in f1:
	words = line[:-1].strip().split()
	dict1[words[0].lower()] += [words[1].lower()]

for line in f2:
	words = line[:-1].strip().split()
	dict2[words[1].lower()] += [words[0].lower()]


combined = {}

keys = list(set(dict1.keys()).union(set(dict2.keys()))) 
fl = open("alignment.txt", "w")

for key in keys:
	size = len(dict1[key] + dict2[key])
	values = Counter(dict1[key] + dict2[key])
	
	value = list(sorted(values.items(), key=lambda x: x[1]))[-1][0]
	
	#for val in values:
	#	values[val] = float(values[val])/size

	#combined[key] = values 
	
	fl.write((" ".join([key, value]) + "\n"))
	

		
	


